title: Cloud-Based CMMS, Asset Maintenance Software & More | Fiix
description: >- # this means to ignore newlines until "baseurl:"
 Fiix's cloud-based maintenance & asset management software organizes, tracks, and schedules your maintenance management activities. Get started for just R600. Official South African reseller for the African Market. Durban, South Africa.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.fiixsoftware.co.za" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

  - jekyll-gzip

