# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cloud-Based CMMS, Asset Maintenance Software & More | Fiix
description: >- # this means to ignore newlines until "baseurl:"
 Fiix's cloud-based maintenance & asset management software organizes, tracks, and schedules your maintenance management activities. Get started for just R600. Official South African reseller for the African Market. Based in Durban, South Africa.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.fiixsoftware.co.za" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

  - jekyll-gzip

